# Numpy

Para importar numpy, utilize: import numpy as np

Você também pode utilizar: from numpy import *. Isso evitará a utilização do np., mas esse comando importará todos os módulos do Numpy.

Para atualizar o Numpy, abra o prompt de comando e digite: pip install numpy -U

In [2]:
# Importando o NumPy
import numpy as np

In [3]:
np.__version__

'1.21.4'

# Criando Arrays

In [4]:
# Help
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [5]:
# Array criado a partir de uma lista:
vetor1 = np.array([0,1,2,3,4,5,6,7,8])

In [6]:
print(vetor1)

[0 1 2 3 4 5 6 7 8]


In [7]:
# Um objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho.
type(vetor1)

numpy.ndarray

In [12]:
# Usando métodos do array Numpy
vetor1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [8]:
# Criando uma lista. Percea como lista e arrayss são objetos diferentes, com diferentes propriedades
lst = [0,1,2,3,4,5,6,7,8]

In [9]:
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [10]:
type(lst)

list

In [11]:
# Imprimindo na tela um elemento específico do array
vetor1[0]

0

In [13]:
# Alterando um elemento do array
vetor1[0] = 100

In [14]:
print(vetor1)

[100   1   2   3   4   5   6   7   8]


In [15]:
# Não é possível incluir elemento de outro tipo
vetor1[0] = 'Novo elemento'

ValueError: invalid literal for int() with base 10: 'Novo elemento'

In [16]:
# Parei no 07:25